DROP TABLE EMPLOYEE;
DROP TABLE DEPARTMENT;

CREATE TABLE DEPARTMENT (
	DEPT_NO NUMBER PRIMARY KEY,
    --DEPT_NO NUMBER NOT NULL PRIMARY KEY,  되고
    --DEPT_NO NUMBER UNIQUE PRIMARY KEY,  안 되고
	DEPT_NAME VARCHAR2(15) NOT NULL,
	LOCATION VARCHAR2(15) NOT NULL
);

CREATE TABLE EMPLOYEE (
	EMP_NO NUMBER PRIMARY KEY,
	NAME VARCHAR2(20) NOT NULL,
	DEPARTMENT NUMBER REFERENCES DEPARTMENT (DEPT_NO),
	POSITION VARCHAR2(20),
	GENDER CHAR(2),
	HIRE_DATE DATE,
	SALARY NUMBER
);

-- 1. INSERT
INSERT INTO DEPARTMENT (DEPT_NO, DEPT_NAME, LOCATION) VALUES (1, '영업부', '대구');
INSERT INTO DEPARTMENT VALUES (2, '인사부', '서울');
INSERT INTO DEPARTMENT VALUES (3, '총무부', '대구');
INSERT INTO DEPARTMENT (DEPT_NO, DEPT_NAME, LOCATION) VALUES (4, '기획부', '서울');

COMMIT;

-- DB에서 날짜로 인식되는 리터럴(표현법: -, /)
/*
    1. 20/10/22
    2. 2020/10/22
    3. 20-10-22
    4. 2020-10-22
*/
INSERT INTO EMPLOYEE VALUES (1001, '구창민', 1, '과장', 'M', '95/05/01', 5000000);
INSERT INTO EMPLOYEE VALUES (1002, '김민서', 1, '사원', 'M', '2017/09/01', 2500000);
INSERT INTO EMPLOYEE VALUES (1003, '이은영', 2, '부장', 'F', '90-09-01', 5500000);
INSERT INTO EMPLOYEE VALUES (1004, '한성일', 2, '과장', 'M', '1993-04-01', 5000000);
COMMIT;

-- 2. UPDATE

UPDATE DEPARTMENT SET LOCATION = '세종' WHERE DEPT_NO = 4;  -- DEPT_NO는 기본키이다. 기본키는 빠른 검색을 위해 설정하는 '인덱스'가 자동지정된다.
UPDATE DEPARTMENT SET LOCATION = '세종' WHERE DEPT_NAME = '기획부';

UPDATE EMPLOYEE SET SALARY = SALARY + 300000 WHERE EMP_NO = 1002;
COMMIT;


-- 3. DELETE
DELETE FROM DEPARTMENT WHERE DEPT_NO = 1;  -- 왜 삭제되지 않는가? 부서번호(DEPT_NO)가 1인 직원(EMPLOYEE)이 현재 2명 있어서.
DELETE FROM DEPARTMENT WHERE DEPT_NO = 3;  -- 잘 삭제된다. 부서번호가 3인 직원이 한 명도 없으므로.

COMMIT;

SELECT DEPT_NO, DEPT_NAME, LOCATION FROM DEPARTMENT;
SELECT * FROM EMPLOYEE;  -- 모든 칼럼을 의미하는 * (성능이 좋지는 않다.)
