-- 직원(EMPLOYEE)
-- 부서(DEPARTMENT)

-- 1. 테이블 삭제 (FK먼저, PK나중)
DROP TABLE EMPLOYEE;
DROP TABLE DEPARTMENT;

-- 2. 테이블 생성 (PK먼저, FK나중)
CREATE TABLE DEPARTMENT (
    DEPT_NO NUMBER PRIMARY KEY,
    DEPT_NAME VARCHAR2(15) NOT NULL,
    LOCATION VARCHAR2(15) NOT NULL
);
CREATE TABLE EMPLOYEE (
    EMP_NO NUMBER PRIMARY KEY,
    NAME VARCHAR2(15) NOT NULL,
    POSITION VARCHAR2(15),
    GENDER VARCHAR2(5),
    SALARY NUMBER,
    HIRE_DATE DATE,
    DEPARTMENT NUMBER REFERENCES DEPARTMENT(DEPT_NO)
);

-- 3. DEPARTMENT 테이블에 ROW 삽입 (PK먼저 ROW삽입)
-- 부서번호: 1, 2, 3, 4
-- 부서명 : 영업부, 인사부, 총무부, 기획부
-- 위치 : 대구, 서울, 대구, 서울
INSERT INTO DEPARTMENT (DEPT_NO, DEPT_NAME, LOCATION) VALUES (1, '영업부', '대구');
INSERT INTO DEPARTMENT (DEPT_NO, DEPT_NAME, LOCATION) VALUES (2, '인사부', '서울');
INSERT INTO DEPARTMENT (DEPT_NO, DEPT_NAME, LOCATION) VALUES (3, '총무부', '대구');
INSERT INTO DEPARTMENT (DEPT_NO, DEPT_NAME, LOCATION) VALUES (4, '기획부', '서울');

-- 4. EMPLOYEE 테이블에 ROW 삽입 (FK나중 ROW삽입)
-- 전체 칼럼에 데이터(ROW)를 삽입하는 경우 삽입할 칼럼명을 생략한다.
-- INSERT INTO 테이블 VALUES (값1, 값2, ... )
INSERT INTO EMPLOYEE VALUES (1001, '구창민', '과장', 'M', 5000000, '95/05/01', 1);
INSERT INTO EMPLOYEE VALUES (1002, '김민서', '사원', 'M', 2500000, '17/09/01', 1);
INSERT INTO EMPLOYEE VALUES (1003, '이은영', '부장', 'F', 5500000, '90/09/01', 2);
INSERT INTO EMPLOYEE VALUES (1004, '한성일', '과장', 'M', 5000000, '93/04/01', 2);










