-- 수강신청 데이터베이스 구축

-- 외래키를 가진 테이블을 먼저 삭제
DROP TABLE LECTURE;
DROP TABLE ENROLL;
DROP TABLE STUDENT;
-- 외래키가 없는 테이블을 나중에 삭제
DROP TABLE COURSE;
DROP TABLE PROFESSOR;


-- 1. PROFESSOR 테이블 (P_NO : 기본키)  -- 부모
CREATE TABLE PROFESSOR (
    P_NO VARCHAR2(10) PRIMARY KEY,  -- 기본키
    P_NAME VARCHAR2(30),
    P_MAJOR VARCHAR2(30)
);

-- 2. COURSE 테이블 (C_NO : 기본키)  -- 부모
CREATE TABLE COURSE (
    C_NO VARCHAR2(10) PRIMARY KEY,  -- 기본키
    C_NAME VARCHAR2(30),
    C_UNIT NUMBER(1)
);

-- 3. STUDENT 테이블 (S_NO : 기본키, P_NO : 외래키)
CREATE TABLE STUDENT (
    S_NO VARCHAR2(10) PRIMARY KEY,  -- 기본키
    S_NAME VARCHAR2(30),
    S_ADDRESS VARCHAR2(100),
    S_GRADE_NO NUMBER(1),
    P_NO VARCHAR2(10) REFERENCES PROFESSOR(P_NO) -- PROFESSOR 테이블의 P_NO 를 참조하는 외래키
);

-- 4. ENROLL 테이블 (E_NO : 기본키, S_NO, C_NO : 외래키)
CREATE TABLE ENROLL (
    E_NO VARCHAR2(10) PRIMARY KEY,
    S_NO VARCHAR2(10) REFERENCES STUDENT(S_NO),  -- STUDENT 테이블의 S_NO 를 참조하는 외래키
    C_NO VARCHAR2(10) REFERENCES COURSE(C_NO),  -- COURSE 테이블의 C_NO 를 참조하는 외래키
    E_DATE DATE
);

-- 5. LECTURE 테이블 (L_NO : 기본키, P_NO, E_NO : 외래키)
CREATE TABLE LECTURE (
    L_NO VARCHAR2(10) PRIMARY KEY,  -- 기본키
    P_NO VARCHAR2(10) REFERENCES PROFESSOR(P_NO),  -- PROFESSOR 테이블의 P_NO 를 참조하는 외래키
    E_NO VARCHAR2(10) REFERENCES ENROLL(E_NO),  -- ENROLL 테이블의 E_NO 를 참조하는 외래키
    L_NAME VARCHAR2(30),
    L_LOCATION VARCHAR2(30)
);


-- 1. PROFESSOR 테이블 데이터 입력
INSERT INTO PROFESSOR VALUES ('1', '제임스', '전산');
INSERT INTO PROFESSOR VALUES ('2', '앨리스', '회계');
INSERT INTO PROFESSOR VALUES ('3', '스미스', '영화');

-- 2. COURSE 테이블 데이터 입력
INSERT INTO COURSE VALUES ('11', '자바', 3);
INSERT INTO COURSE VALUES ('22', '데이터베이스', 3);
INSERT INTO COURSE VALUES ('33', '서버프로그램', 3);

-- 3. STUDENT 테이블 데이터 입력
INSERT INTO STUDENT VALUES ('10101', '김학생', '서울', 1, 3);
INSERT INTO STUDENT VALUES ('10102', '이학생', '서울', 1, 3);
INSERT INTO STUDENT VALUES ('10103', '박학생', '서울', 1, 3);

-- 4. ENROLL 테이블 데이터 입력
INSERT INTO ENROLL VALUES ('111', '10101', '11', SYSDATE);
INSERT INTO ENROLL VALUES ('222', '10101', '22', SYSDATE);
INSERT INTO ENROLL VALUES ('333', '10101', '33', SYSDATE);

-- 5. LECTURE 테이블 데이터 입력
INSERT INTO LECTURE VALUES ('1111', '1', '111', '자바완전정복', 'A101');
INSERT INTO LECTURE VALUES ('2222', '1', '111', '자바완전정복', 'B101');
INSERT INTO LECTURE VALUES ('3333', '1', '111', '자바완전정복', 'C104');

-- 6. 변경된 내용을 DB 에 저장한다.
COMMIT;  -- INSERT, UPDATE, DELETE 문은 필요
