-- 시퀀스
DROP SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 999999 NOCYCLE NOCACHE;
DROP SEQUENCE GUEST_SEQ;
CREATE SEQUENCE GUEST_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 999999 NOCYCLE NOCACHE;
DROP SEQUENCE BBS_SEQ;
CREATE SEQUENCE BBS_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 999999 NOCYCLE NOCACHE;
DROP SEQUENCE REPLY_SEQ;
CREATE SEQUENCE REPLY_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 999999 NOCYCLE NOCACHE;


-- 테이블
DROP TABLE MEMBER;
CREATE TABLE MEMBER
(
	MNO NUMBER PRIMARY KEY,
	MID VARCHAR2(30) NOT NULL UNIQUE,
	MPW VARCHAR2(30) NOT NULL,
	MNAME VARCHAR2(30),
	MEMAIL VARCHAR2(50) NOT NULL UNIQUE,
	MPHONE VARCHAR2(20),
	MADDRESS VARCHAR2(100),
	MREGDATE DATE
);

DROP TABLE GUEST;
CREATE TABLE GUEST 
(
	GNO NUMBER PRIMARY KEY,
	GWRITER VARCHAR2(100) NOT NULL,
	GTITLE VARCHAR2(1000) NOT NULL,
	GCONTENT VARCHAR2(4000),
	GPW VARCHAR2(20) NOT NULL,
	GFILENAME VARCHAR2(300),
	GPOSTDATE DATE
);

DROP TABLE REPLY;
DROP TABLE BBS;

CREATE TABLE BBS
(
	BBS_NO NUMBER PRIMARY KEY,
	BBS_WRITER VARCHAR2(100) NOT NULL,
	BBS_TITLE VARCHAR2(1000) NOT NULL,
	BBS_CONTENT VARCHAR2(4000),
	BBS_PW VARCHAR2(20) NOT NULL,
	BBS_HIT NUMBER,
	BBS_IP VARCHAR2(20),
	BBS_DATE DATE
);
CREATE TABLE REPLY
(
	RNO NUMBER PRIMARY KEY,
	RWRITER VARCHAR2(100) NOT NULL,
	RCONTENT VARCHAR2(4000),
	RPW VARCHAR2(20) NOT NULL,
	RIP VARCHAR2(20),
	RDATE DATE,
	BBS_NO NUMBER REFERENCES BBS(BBS_NO)
);



INSERT INTO MEMBER VALUES (MEMBER_SEQ.NEXTVAL, 'admin', '1111', '관리자', 'admin@myhome.com', '010-0000-0000', 'seoul', SYSDATE);
